#!/bin/bash
######################################
#Purpose: To learn shell script
#Version: 1.0
#Owner  : Kapil <kapil0123@gmail.com>
#Input  : None
#Output : None
######################################

SEARCH=$1                               #1st argument
REPLACE=$2                              #2nd argument
FILE_NAME=$3
                                        #if [ ! ( "$SEARCH" ) -a ( "$REPLACE" ) ]; then
                                        #CAL= "0 -a 0"
                                        #if [ ! ( 0 -a 0 ) ] ); then
if [ ! "$FILE_NAME" ]; then
echo "Enter 3 agr 1st search 2nd replace 3rd filename with extension "
exit
fi
                                        #sed 's/\<apple\>/pineapple/' fruit
sed  "s/\<$SEARCH\>/$REPLACE/I" $FILE_NAME #-i is used for change in file

